In [19]:
print(1)

1

In [20]:
import pandas as pd
import numpy as np

# from google.colab import drive
# drive.mount('/content/gdrive')
# DATA_PATH = '/content/gdrive/MyDrive/REU/PROJECT/DATA/'
DATA_PATH = "/home/jovyan/work/ner_congressional_records/DATA/"

In [21]:
mi_annotated = pd.read_csv(DATA_PATH+"mi_annotated_data.csv")
mn_annotated = pd.read_csv(DATA_PATH+"mn_annotated_data.csv")

In [22]:
mi_annotated

,Unnamed: 0,merged_full_name,transactor_type
0,1667,butzel long pac butzel long political action c...,Organization
1,1668,retired detroit police/fire assn pac retired d...,Organization
2,1669,committee to elect gene haymaker committee to ...,Organization
3,1670,jack coleman for state representativ jack cole...,Organization
4,1671,tuscola county republican party tuscola county...,Organization
...,...,...,...
2149,1954544,committee to elect jeremiah buffalo committee ...,Organization
2150,1954579,jonathan hoover jonathan hoover,Organization
2151,1955959,miller for michigan miller for michigan,Organization
2152,1956014,southwest michigan building trades p southwest...,Organization
2153,1956999,douglas waggener campaign committee douglas ...,Organization

In [23]:
mn_annotated

       Unnamed: 0                    merged_full_name transactor_type
0             833                      rhode, peter s      Individual
1             834                      machayya, mark      Individual
2             835                       lovaasen, tim      Individual
3             836                          yang, adam      Individual
4             837                        elko, thomas      Individual
...           ...                                 ...             ...
74545      941633       young progressive majority mn    Organization
74546      944391      kaiser, jamie senate committee    Organization
74547      945886  cragg, daniel dist court committee    Organization
74548      948410    anderson, darrin house committee    Organization
74549      963047                               rypac    Organization

[74550 rows x 3 columns]

In [24]:
annotated = mn_annotated[['merged_full_name', 'transactor_type']].copy()

In [25]:
annotated = pd.concat([mi_annotated, mn_annotated])

In [26]:
annotated

,Unnamed: 0,merged_full_name,transactor_type
0,1667,butzel long pac butzel long political action c...,Organization
1,1668,retired detroit police/fire assn pac retired d...,Organization
2,1669,committee to elect gene haymaker committee to ...,Organization
3,1670,jack coleman for state representativ jack cole...,Organization
4,1671,tuscola county republican party tuscola county...,Organization
...,...,...,...
74545,941633,young progressive majority mn,Organization
74546,944391,"kaiser, jamie senate committee",Organization
74547,945886,"cragg, daniel dist court committee",Organization
74548,948410,"anderson, darrin house committee",Organization
74549,963047,rypac,Organization

In [27]:
annotated.to_csv(DATA_PATH+"mi_mn_annotated.csv")

PermissionError: [Errno 13] Permission denied: '/home/jovyan/work/ner_congressional_records/DATA/mi_mn_annotated.csv'